-- ============================================================================
-- seed-dev-data.sql — development login accounts (P2 exit criterion)
--
-- WHY THIS FILE IS SMALLER THAN THE NAME SUGGESTS
-- The plan asked for "vehicles, dealers, admin user". Two of those three are
-- ALREADY seeded, and not by this file: VehicleService/DbContext declares them
-- with HasData (ApplicationDbContext.cs:64, :74, :122, :196, :257, :272), which
-- EF bakes into the Baseline migration as INSERTs. Measured on the running
-- stack: 6 VehicleTypes, 4 Dealers, 5 Vehicles — present before this script
-- existed. Re-inserting them here would be a second source of truth for the
-- same rows, and would break the moment anyone edited a seeded vehicle
-- through the API: EF's next migration would diff its HasData value against
-- what is in the database and emit a corrective UPDATE.
--
-- So this script seeds only what is genuinely missing: USERS. Measured before
-- writing this file: `SELECT count(*) FROM "Users"` returned 0 — a developer
-- running the stack has no account to log in with, and cannot create one
-- because RegisterAsync sets IsActive = false and only an Admin can approve
-- (UserServiceImpl.cs:66), and Admin creation requires being logged in already.
-- That is the chicken-and-egg this file breaks.
--
-- IDEMPOTENT
-- Run it as many times as you like. Inserts are keyed on the unique index
-- IX_Users_Username (verified: CREATE UNIQUE INDEX "IX_Users_Username"),
-- and every account is inserted only when absent. Nothing is UPDATEd, so
-- re-running after you changed a password or a role leaves your change alone.
--
-- Re-running the migration is the escape hatch if you want the pristine
-- values back: those rows are HasData-free, so delete them first — see the
-- "reset" section at the bottom.
--
-- THE PASSWORDS ARE BCrypt, GENERATED BY THE SAME LIBRARY THE SERVICE USES
-- BCrypt.Net-Next 4.0.2 (UserService.csproj), default work factor 11. Each
-- hash below was produced by calling BCrypt.Net.BCrypt.HashPassword on its
-- password and then verifying it with BCrypt.Net-BCrypt.Verify — the same
-- pair UserServiceImpl.cs:63 / :128 uses. So these are not hand-written
-- placeholders that would fail verification at the login screen; they are
-- real hashes for the real passwords.
--
-- These are DEVELOPMENT credentials. Never load this file into any
-- environment whose data anyone but you can see.
--
-- HOW TO RUN
--   docker compose exec -T postgres psql -U postgres -d evm_core < seed-dev-data.sql
--
-- or against any other Postgres, replacing user/database:
--   psql -U <user> -d <db> -f seed-dev-data.sql
--
-- Requires PostgreSQL 10+ (ON CONFLICT) — Render's image and the
-- postgres:16 in docker-compose.yml both qualify.
-- ============================================================================

\set ON_ERROR_STOP on

BEGIN;

-- ---------------------------------------------------------------------------
-- Admin (the account that can approve the accounts below, and the only role
-- UserServiceImpl.CreateApprovedUserAsync accepts from itself: :82)
-- ---------------------------------------------------------------------------
INSERT INTO "Users" ("Username", "Email", "FullName", "PasswordHash", "Role", "IsActive", "DealerId", "CreatedAt", "UpdatedAt")
SELECT 'admin', 'admin@evdealer.local', 'EVM Administrator',
       '$2a$11$Cp4aF4MrB4brZml4uiO7KujTRrzcD5Ttb5/CRxBYXecJOFV9YluvO',
       'Admin', true, NULL, now(), now()
WHERE NOT EXISTS (SELECT 1 FROM "Users" WHERE "Username" = 'admin');

-- ---------------------------------------------------------------------------
-- EVM staff — manufacturer-side user. Role from the register allow-list at
-- UserServiceImpl.cs:36. No DealerId: this account is not tied to a showroom.
-- ---------------------------------------------------------------------------
INSERT INTO "Users" ("Username", "Email", "FullName", "PasswordHash", "Role", "IsActive", "DealerId", "CreatedAt", "UpdatedAt")
SELECT 'evm.staff', 'evm.staff@evdealer.local', 'EVM Staff',
       '$2a$11$.SjRyvnQBzhAXpB0ovyjTuLdvRkegFti3cPV57fJHN5.0hhSHPwvm',
       'EVMStaff', true, NULL, now(), now()
WHERE NOT EXISTS (SELECT 1 FROM "Users" WHERE "Username" = 'evm.staff');

-- ---------------------------------------------------------------------------
-- Dealer manager, bound to dealer 1 (Tesla Center HCMC). DealerId 1 is a
-- seeded HasData row, verified present; the users -> dealers link is NOT a
-- database foreign key (Entities.cs:19-30 explains UserService no longer maps
-- the Dealers table), so the only thing tying this to a showroom is the id
-- itself. It also becomes a "dealer" JWT claim at UserServiceImpl.cs:148-149,
-- which is what lets this account manage dealer:1 push-token subjects.
-- ---------------------------------------------------------------------------
INSERT INTO "Users" ("Username", "Email", "FullName", "PasswordHash", "Role", "IsActive", "DealerId", "CreatedAt", "UpdatedAt")
SELECT 'dealer.hcm', 'dealer.hcm@evdealer.local', 'Dealer Manager — Tesla Center HCMC',
       '$2a$11$hCF3uMNfA9RC2w36UpO8uOCmXgjxwPjbldHg7NhITDeoC2hs.vX9e',
       'DealerManager', true, 1, now(), now()
WHERE NOT EXISTS (SELECT 1 FROM "Users" WHERE "Username" = 'dealer.hcm');

COMMIT;

-- ---------------------------------------------------------------------------
-- Report what happened, so a first run is visibly different from a re-run.
-- ---------------------------------------------------------------------------
SELECT "Username", "Role", "IsActive", "DealerId"
FROM "Users"
WHERE "Username" IN ('admin', 'evm.staff', 'dealer.hcm')
ORDER BY "Username";

-- ============================================================================
-- RESET — only if you want the pristine values back.
--
-- These three rows are plain INSERTs, NOT HasData, so EF does not own them
-- and no migration will restore them for you. Delete and re-run this file:
--
--   DELETE FROM "Users" WHERE "Username" IN ('admin', 'evm.staff', 'dealer.hcm');
--
-- Do NOT put that DELETE at the top of this file. Running this script is then
-- no longer idempotent in the way that matters: it would silently discard a
-- password you changed, and someone would discover that by failing to log in.
-- ============================================================================
