using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace Common.Data;

// Issue #89: single source of truth for the provider switch.
//
// Two claims from the original recon were probed and refuted before this was
// written, and both are worth recording because they will look true to anyone
// reading the migrations:
//
// 1. "EnsureCreated() skips HasData seed rows." FALSE under Microsoft.Data.Sqlite
//    — a probe against a real SQLite FILE (not :memory:) produced
//    VehicleTypes 6 / Dealers 4 / Vehicles 5 / Specs 5 / Images 11 / Colors 14
//    from EnsureCreated() alone. The rule is provider-specific folklore, and
//    VehicleService's seeding is fine as shipped (#88, closed invalid).
//
// 2. "The Sqlite:Autoincrement annotations break int PKs on Postgres — Npgsql
//    ignores them so no sequence is created and every INSERT throws 23502."
//    Also FALSE. Npgsql's convention layer reads ValueGeneratedOnAdd() off the
//    model snapshot and adds Npgsql:ValueGenerationStrategy = IdentityByDefaultColumn
//    on its own. GenerateCreateScript() under UseNpgsql emits
//    "Id" integer GENERATED BY DEFAULT AS IDENTITY without any annotation edits.
//    The Sqlite: annotation is simply irrelevant under the other provider; it
//    does not need to be removed and no dual annotation is required.
//
// So the migration files stay UNTOUCHED. What actually differs per provider is
// only the connection setup, which is what this helper centralises.
public static class DbProviderSelector
{
    // "sqlite" (or unset) keeps every existing local, CI and compose path
    // byte-identical. "postgres" switches the provider AND hard-fails if the
    // server is unreachable — deliberately NOT ReportingService's
    // probe-and-silently-fall-back-to-SQLite pattern (Program.cs:84-96): in
    // production a silent fallback means a misconfigured service quietly boots
    // on SQLite and loses everything written to the container layer on the next
    // redeploy. Failing loudly is the correct failure mode.
    public static void AddApplicationDbContext<TContext>(
        this IServiceCollection services,
        IConfiguration configuration,
        string connectionStringName = "DefaultConnection",
        string? sqliteFallback = null,
        Action<DbContextOptionsBuilder>? configureOptions = null)
        where TContext : DbContext
    {
        var provider = (configuration["DB_PROVIDER"] ?? "sqlite").Trim()
                          .ToLowerInvariant();
        var connectionString = configuration.GetConnectionString(connectionStringName);

        // Unknown values do NOT fall through to SQLite. The whole point of this
        // helper (see the class comment) is that a misconfigured service must
        // fail loudly instead of quietly booting on SQLite and losing data on
        // the next redeploy — a typo like "postgre" or a future "sqlserver"
        // taking a silent SQLite path would be exactly that failure mode.
        switch (provider)
        {
            case "postgres":
            case "postgresql":
                if (string.IsNullOrWhiteSpace(connectionString))
                    throw new InvalidOperationException(
                        $"DB_PROVIDER=postgres but ConnectionStrings:{connectionStringName} is unset. " +
                        "Set it to a PostgreSQL connection string (Host=...;Database=...).");

                services.AddDbContext<TContext>(options =>
                {
                    options.UseNpgsql(connectionString);
                    configureOptions?.Invoke(options);
                });
                Console.WriteLine($"DB_PROVIDER=postgres: {typeof(TContext).Name} on PostgreSQL");
                break;

            case "sqlite":
                if (string.IsNullOrWhiteSpace(connectionString))
                    connectionString = sqliteFallback;
                if (string.IsNullOrWhiteSpace(connectionString))
                    throw new InvalidOperationException(
                        $"ConnectionStrings:{connectionStringName} is unset and no SQLite fallback was supplied.");

                services.AddDbContext<TContext>(options =>
                {
                    options.UseSqlite(connectionString);
                    configureOptions?.Invoke(options);
                });
                break;

            default:
                throw new InvalidOperationException(
                    $"DB_PROVIDER='{provider}' is not a supported value. " +
                    "Use 'sqlite' (default) or 'postgres'.");
        }
    }
}
