// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleService.Data;

#nullable disable

namespace VehicleService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260916102547_UpdateSeedVehicleImagesToWwwroot")]
    partial class UpdateSeedVehicleImagesToWwwroot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("VehicleService.Models.ColorVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("ColorVariants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hex = "#FFFFFF",
                            Name = "Pearl White",
                            Stock = 5,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Hex = "#2C2C2C",
                            Name = "Midnight Silver",
                            Stock = 4,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 3,
                            Hex = "#1E3A8A",
                            Name = "Deep Blue",
                            Stock = 3,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 4,
                            Hex = "#FFFFFF",
                            Name = "Pearl White",
                            Stock = 3,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 5,
                            Hex = "#2C2C2C",
                            Name = "Midnight Silver",
                            Stock = 3,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 6,
                            Hex = "#DC2626",
                            Name = "Red Multi-Coat",
                            Stock = 2,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 7,
                            Hex = "#FFFFFF",
                            Name = "Alpine White",
                            Stock = 2,
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 8,
                            Hex = "#F5F5F5",
                            Name = "Mineral White",
                            Stock = 2,
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 9,
                            Hex = "#000000",
                            Name = "Black Sapphire",
                            Stock = 2,
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 10,
                            Hex = "#FFFFFF",
                            Name = "Glacier White",
                            Stock = 2,
                            VehicleId = 4
                        },
                        new
                        {
                            Id = 11,
                            Hex = "#000000",
                            Name = "Mythos Black",
                            Stock = 1,
                            VehicleId = 4
                        },
                        new
                        {
                            Id = 12,
                            Hex = "#C8102E",
                            Name = "Tango Red",
                            Stock = 1,
                            VehicleId = 4
                        },
                        new
                        {
                            Id = 13,
                            Hex = "#000000",
                            Name = "Obsidian Black",
                            Stock = 1,
                            VehicleId = 5
                        },
                        new
                        {
                            Id = 14,
                            Hex = "#FFFFFF",
                            Name = "Diamond White",
                            Stock = 1,
                            VehicleId = 5
                        });
                });

            modelBuilder.Entity("VehicleService.Models.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dealers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Nguyen Hue, District 1, HCMC",
                            Contact = "0901234567",
                            CreatedAt = new DateTime(2026, 9, 16, 10, 25, 47, 563, DateTimeKind.Utc).AddTicks(5177),
                            Email = "hcmc@tesla.com",
                            Name = "Tesla Center HCMC",
                            Region = "Ho Chi Minh City",
                            UpdatedAt = new DateTime(2026, 9, 16, 10, 25, 47, 563, DateTimeKind.Utc).AddTicks(5177)
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Le Loi, District 1, HCMC",
                            Contact = "0902345678",
                            CreatedAt = new DateTime(2026, 9, 16, 10, 25, 47, 563, DateTimeKind.Utc).AddTicks(5179),
                            Email = "district1@bmw.com",
                            Name = "BMW Center District 1",
                            Region = "Ho Chi Minh City",
                            UpdatedAt = new DateTime(2026, 9, 16, 10, 25, 47, 563, DateTimeKind.Utc).AddTicks(5180)
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Dong Khoi, District 2, HCMC",
                            Contact = "0903456789",
                            CreatedAt = new DateTime(2026, 9, 16, 10, 25, 47, 563, DateTimeKind.Utc).AddTicks(5182),
                            Email = "district2@audi.com",
                            Name = "Audi Center District 2",
                            Region = "Ho Chi Minh City",
                            UpdatedAt = new DateTime(2026, 9, 16, 10, 25, 47, 563, DateTimeKind.Utc).AddTicks(5182)
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Nguyen Van Cu, District 3, HCMC",
                            Contact = "0904567890",
                            CreatedAt = new DateTime(2026, 9, 16, 10, 25, 47, 563, DateTimeKind.Utc).AddTicks(5184),
                            Email = "district3@mercedes.com",
                            Name = "Mercedes-Benz Center District 3",
                            Region = "Ho Chi Minh City",
                            UpdatedAt = new DateTime(2026, 9, 16, 10, 25, 47, 563, DateTimeKind.Utc).AddTicks(5184)
                        });
                });

            modelBuilder.Entity("VehicleService.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BatteryCapacity")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DealerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VehicleTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatteryCapacity = 75.0,
                            CreatedAt = new DateTime(2026, 9, 16, 10, 25, 47, 563, DateTimeKind.Utc).AddTicks(5223),
                            DealerId = 1,
                            Description = "Premium electric sedan with autopilot capabilities",
                            Model = "Tesla Model 3",
                            Price = 45000m,
                            Range = 350,
                            StockQuantity = 12,
                            Type = "sedan",
                            UpdatedAt = new DateTime(2026, 9, 16, 10, 25, 47, 563, DateTimeKind.Utc).AddTicks(5223)
                        },
                        new
                        {
                            Id = 2,
                            BatteryCapacity = 75.0,
                            CreatedAt = new DateTime(2026, 9, 16, 10, 25, 47, 563, DateTimeKind.Utc).AddTicks(5226),
                            DealerId = 1,
                            Description = "Versatile electric SUV perfect for families",
                            Model = "Tesla Model Y",
                            Price = 55000m,
                            Range = 330,
                            StockQuantity = 8,
                            Type = "suv",
                            UpdatedAt = new DateTime(2026, 9, 16, 10, 25, 47, 563, DateTimeKind.Utc).AddTicks(5226)
                        },
                        new
                        {
                            Id = 3,
                            BatteryCapacity = 83.900000000000006,
                            CreatedAt = new DateTime(2026, 9, 16, 10, 25, 47, 563, DateTimeKind.Utc).AddTicks(5229),
                            DealerId = 2,
                            Description = "Luxury electric sedan with BMW's signature driving dynamics",
                            Model = "BMW i4",
                            Price = 52000m,
                            Range = 300,
                            StockQuantity = 6,
                            Type = "sedan",
                            UpdatedAt = new DateTime(2026, 9, 16, 10, 25, 47, 563, DateTimeKind.Utc).AddTicks(5229)
                        },
                        new
                        {
                            Id = 4,
                            BatteryCapacity = 95.0,
                            CreatedAt = new DateTime(2026, 9, 16, 10, 25, 47, 563, DateTimeKind.Utc).AddTicks(5232),
                            DealerId = 3,
                            Description = "Premium electric SUV with quattro all-wheel drive",
                            Model = "Audi e-tron",
                            Price = 65000m,
                            Range = 222,
                            StockQuantity = 4,
                            Type = "suv",
                            UpdatedAt = new DateTime(2026, 9, 16, 10, 25, 47, 563, DateTimeKind.Utc).AddTicks(5232)
                        },
                        new
                        {
                            Id = 5,
                            BatteryCapacity = 107.8,
                            CreatedAt = new DateTime(2026, 9, 16, 10, 25, 47, 563, DateTimeKind.Utc).AddTicks(5234),
                            DealerId = 4,
                            Description = "Ultra-luxury electric sedan with cutting-edge technology",
                            Model = "Mercedes EQS",
                            Price = 120000m,
                            Range = 350,
                            StockQuantity = 2,
                            Type = "sedan",
                            UpdatedAt = new DateTime(2026, 9, 16, 10, 25, 47, 563, DateTimeKind.Utc).AddTicks(5235)
                        });
                });

            modelBuilder.Entity("VehicleService.Models.VehicleImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AltText")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AltText = "Tesla Model 3 Front",
                            Order = 1,
                            Url = "/images/seed-car1.webp",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            AltText = "Tesla Model 3 Side",
                            Order = 2,
                            Url = "/images/seed-car2.webp",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 3,
                            AltText = "Tesla Model 3 Interior",
                            Order = 3,
                            Url = "/images/seed-car3.webp",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 4,
                            AltText = "Tesla Model Y Front",
                            Order = 1,
                            Url = "/images/seed-car2.webp",
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 5,
                            AltText = "Tesla Model Y Side",
                            Order = 2,
                            Url = "/images/seed-car3.webp",
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 6,
                            AltText = "Tesla Model Y Interior",
                            Order = 3,
                            Url = "/images/seed-car4.webp",
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 7,
                            AltText = "BMW i4 Front",
                            Order = 1,
                            Url = "/images/seed-car3.webp",
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 8,
                            AltText = "BMW i4 Side",
                            Order = 2,
                            Url = "/images/seed-car4.webp",
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 9,
                            AltText = "Audi e-tron Front",
                            Order = 1,
                            Url = "/images/seed-car4.webp",
                            VehicleId = 4
                        },
                        new
                        {
                            Id = 10,
                            AltText = "Mercedes EQS Front",
                            Order = 1,
                            Url = "/images/seed-car1.webp",
                            VehicleId = 5
                        },
                        new
                        {
                            Id = 11,
                            AltText = "Mercedes EQS Side",
                            Order = 2,
                            Url = "/images/seed-car2.webp",
                            VehicleId = 5
                        });
                });

            modelBuilder.Entity("VehicleService.Models.VehicleSpecifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Acceleration")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Charging")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Seats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopSpeed")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Warranty")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("VehicleSpecifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acceleration = "3.1s 0-60mph",
                            Cargo = "15 cu ft",
                            Charging = "250 kW Supercharging",
                            Seats = 5,
                            TopSpeed = "162 mph",
                            VehicleId = 1,
                            Warranty = "4 years/50,000 miles"
                        },
                        new
                        {
                            Id = 2,
                            Acceleration = "3.5s 0-60mph",
                            Cargo = "76 cu ft",
                            Charging = "250 kW Supercharging",
                            Seats = 7,
                            TopSpeed = "155 mph",
                            VehicleId = 2,
                            Warranty = "4 years/50,000 miles"
                        },
                        new
                        {
                            Id = 3,
                            Acceleration = "3.9s 0-60mph",
                            Cargo = "16 cu ft",
                            Charging = "150 kW DC Fast Charging",
                            Seats = 5,
                            TopSpeed = "118 mph",
                            VehicleId = 3,
                            Warranty = "4 years/50,000 miles"
                        },
                        new
                        {
                            Id = 4,
                            Acceleration = "5.5s 0-60mph",
                            Cargo = "27.2 cu ft",
                            Charging = "150 kW DC Fast Charging",
                            Seats = 5,
                            TopSpeed = "124 mph",
                            VehicleId = 4,
                            Warranty = "4 years/50,000 miles"
                        },
                        new
                        {
                            Id = 5,
                            Acceleration = "4.3s 0-60mph",
                            Cargo = "22 cu ft",
                            Charging = "200 kW DC Fast Charging",
                            Seats = 5,
                            TopSpeed = "130 mph",
                            VehicleId = 5,
                            Warranty = "4 years/50,000 miles"
                        });
                });

            modelBuilder.Entity("VehicleService.Models.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Sedan",
                            Value = "sedan"
                        },
                        new
                        {
                            Id = 2,
                            Label = "SUV",
                            Value = "suv"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Hatchback",
                            Value = "hatchback"
                        },
                        new
                        {
                            Id = 4,
                            Label = "Coupe",
                            Value = "coupe"
                        },
                        new
                        {
                            Id = 5,
                            Label = "Convertible",
                            Value = "convertible"
                        },
                        new
                        {
                            Id = 6,
                            Label = "Truck",
                            Value = "truck"
                        });
                });

            modelBuilder.Entity("VehicleService.Models.ColorVariant", b =>
                {
                    b.HasOne("VehicleService.Models.Vehicle", "Vehicle")
                        .WithMany("ColorVariants")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleService.Models.Vehicle", b =>
                {
                    b.HasOne("VehicleService.Models.Dealer", "Dealer")
                        .WithMany("Vehicles")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehicleService.Models.VehicleType", null)
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleTypeId");

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("VehicleService.Models.VehicleImage", b =>
                {
                    b.HasOne("VehicleService.Models.Vehicle", "Vehicle")
                        .WithMany("Images")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleService.Models.VehicleSpecifications", b =>
                {
                    b.HasOne("VehicleService.Models.Vehicle", "Vehicle")
                        .WithOne("Specifications")
                        .HasForeignKey("VehicleService.Models.VehicleSpecifications", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleService.Models.Dealer", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VehicleService.Models.Vehicle", b =>
                {
                    b.Navigation("ColorVariants");

                    b.Navigation("Images");

                    b.Navigation("Specifications");
                });

            modelBuilder.Entity("VehicleService.Models.VehicleType", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
